spring.application.name=Sportimo
spring.datasource.url=jdbc:mysql://localhost:3306/sportimo
spring.datasource.username=root
spring.datasource.password=mosql

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

message.encryption.secret=${MESSAGE_ENCRYPTION_SECRET:SportimoMessageSecretChangeMe}
